### ISSUE TITLE
/usr/etc is not allowed by FHS (Filesystem Hierarchy Standard)

### ISSUE THREAD

**Issue by mvidner** [thkukuk/atomic-updates_and_etc#2]
[openSUSE Portal:Packaging](https://en.opensuse.org/Portal:Packaging) says 

> We also follow the Linux Filesystem Hierarchy Standard (FHS) which is a reference on how to manage a Linux filesystem hierarchy.

[FHS 3.0, section 4.9  /usr/local : Local hierarchy](https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html) mentions:

> Note that /usr/etc is still not allowed: programs in /usr should place configuration files in /etc. 

What is our plan for resolving this conflict?

**Comment by thkukuk** [comment]
FHS sees itself as "best practice" only, they are not willing to modify anything. There are several requests from SUSE and RedHat, the oldest is I think 4-5 years old. Since there will not happen anything, we have to ignore that. See the discussions RedHat had with them and we had with them.
As the FHS is currently nearly as dead as LSB, we can only ignore it if we don't want to stop and kill all innovation. systemd e.g. is also violating the FHS ...

**Comment by mvidner** [comment]
Fine, thank you!
